# config/routes.yaml
index:
    path: /
    controller: App\Controller\TranscriptionController::index

upload_file:
    path: /upload
    controller: App\Controller\TranscriptionController::upload
    methods: POST

download_file:
    path: /download/{filename}
    controller: App\Controller\TranscriptionController::download
    methods: GET
